; Generated by c86 (BYU-NASM) 5.1 (beta) from lab4app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
main:
	; >>>>> Line:	7
	; >>>>> { 
	jmp	L_lab4app_1
L_lab4app_2:
	; >>>>> Line:	8
	; >>>>> YKInitialize(); 
	call	YKInitialize
	; >>>>> Line:	9
	; >>>>> printChar('e'); 
	mov	al, 101
	push	ax
	call	printChar
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_lab4app_1:
	push	bp
	mov	bp, sp
	jmp	L_lab4app_2
