; Generated by c86 (BYU-NASM) 5.1 (beta) from lab7inth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
myreset:
	; >>>>> Line:	18
	; >>>>> { 
	jmp	L_lab7inth_1
L_lab7inth_2:
	; >>>>> Line:	19
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_lab7inth_1:
	push	bp
	mov	bp, sp
	jmp	L_lab7inth_2
	ALIGN	2
mytick:
	; >>>>> Line:	23
	; >>>>> { 
	jmp	L_lab7inth_4
L_lab7inth_5:
	; >>>>> Line:	25
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_lab7inth_4:
	push	bp
	mov	bp, sp
	jmp	L_lab7inth_5
L_lab7inth_8:
	DB	") IGNORED",0xA,0
L_lab7inth_7:
	DB	0xA,"KEYPRESS (",0
	ALIGN	2
KeyboardHandler:
	; >>>>> Line:	28
	; >>>>> { 
	jmp	L_lab7inth_9
L_lab7inth_10:
	; >>>>> Line:	30
	; >>>>> c = KeyBuffer; 
	mov	al, byte [KeyBuffer]
	mov	byte [bp-1], al
	; >>>>> Line:	32
	; >>>>> if(c == 'a') YKEventSet(charEvent, 0x1); 
	cmp	byte [bp-1], 97
	jne	L_lab7inth_11
	; >>>>> Line:	32
	; >>>>> if(c == 'a') YKEventSet(charEvent, 0x1); 
	mov	ax, 1
	push	ax
	push	word [charEvent]
	call	YKEventSet
	add	sp, 4
	jmp	L_lab7inth_12
L_lab7inth_11:
	; >>>>> Line:	33
	; >>>>> else if(c == 'b') YKEventSet(charEvent, 0x2); 
	cmp	byte [bp-1], 98
	jne	L_lab7inth_13
	; >>>>> Line:	33
	; >>>>> else if(c == 'b') YKEventSet(charEvent, 0x2); 
	mov	ax, 2
	push	ax
	push	word [charEvent]
	call	YKEventSet
	add	sp, 4
	jmp	L_lab7inth_14
L_lab7inth_13:
	; >>>>> Line:	34
	; >>>>> else if(c == 'c') YKEventSet(charEvent, 0x4); 
	cmp	byte [bp-1], 99
	jne	L_lab7inth_15
	; >>>>> Line:	34
	; >>>>> else if(c == 'c') YKEventSet(charEvent, 0x4); 
	mov	ax, 4
	push	ax
	push	word [charEvent]
	call	YKEventSet
	add	sp, 4
	jmp	L_lab7inth_16
L_lab7inth_15:
	; >>>>> Line:	35
	; >>>>> else if(c == 'd') YKEventSet(charEvent, 0x1 | 0x2 | 0x4); 
	cmp	byte [bp-1], 100
	jne	L_lab7inth_17
	; >>>>> Line:	35
	; >>>>> else if(c == 'd') YKEventSet(charEvent, 0x1 | 0x2 | 0x4); 
	mov	ax, 7
	push	ax
	push	word [charEvent]
	call	YKEventSet
	add	sp, 4
	jmp	L_lab7inth_18
L_lab7inth_17:
	; >>>>> Line:	36
	; >>>>> else if(c == '1') YKEventSet(numEvent 
	cmp	byte [bp-1], 49
	jne	L_lab7inth_19
	; >>>>> Line:	36
	; >>>>> else if(c == '1') YKEventSet(numEvent 
	mov	ax, 1
	push	ax
	push	word [numEvent]
	call	YKEventSet
	add	sp, 4
	jmp	L_lab7inth_20
L_lab7inth_19:
	; >>>>> Line:	37
	; >>>>> else if(c == '2') YKEventSet(numEvent, 0x2); 
	cmp	byte [bp-1], 50
	jne	L_lab7inth_21
	; >>>>> Line:	37
	; >>>>> else if(c == '2') YKEventSet(numEvent, 0x2); 
	mov	ax, 2
	push	ax
	push	word [numEvent]
	call	YKEventSet
	add	sp, 4
	jmp	L_lab7inth_22
L_lab7inth_21:
	; >>>>> Line:	38
	; >>>>> else if(c == '3') YKEventSet(numEvent, 0x4); 
	cmp	byte [bp-1], 51
	jne	L_lab7inth_23
	; >>>>> Line:	38
	; >>>>> else if(c == '3') YKEventSet(numEvent, 0x4); 
	mov	ax, 4
	push	ax
	push	word [numEvent]
	call	YKEventSet
	add	sp, 4
	jmp	L_lab7inth_24
L_lab7inth_23:
	; >>>>> Line:	40
	; >>>>> print("\nKEYPRESS (", 11); 
	mov	ax, 11
	push	ax
	mov	ax, L_lab7inth_7
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	41
	; >>>>> printChar(c); 
	push	word [bp-1]
	call	printChar
	add	sp, 2
	; >>>>> Line:	42
	; >>>>> print(") IGNORED\n", 10); 
	mov	ax, 10
	push	ax
	mov	ax, L_lab7inth_8
	push	ax
	call	print
	add	sp, 4
L_lab7inth_24:
L_lab7inth_22:
L_lab7inth_20:
L_lab7inth_18:
L_lab7inth_16:
L_lab7inth_14:
L_lab7inth_12:
	mov	sp, bp
	pop	bp
	ret
L_lab7inth_9:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_lab7inth_10
